### ISSUE TITLE
Failed to load the rewrite_tag_filter with out_rewrite_tag_filter.rb:38:in ``': No such file or directory - hostname (Errno::ENOENT)

### ISSUE THREAD

**Issue by dimalbaby** [fluent/fluent-plugin-rewrite-tag-filter#100]
Hi,
I am trying to build the fluentd on a photon os. I am getting this exception while loading the plugin . Can someone please help me on this?

Fluentd: 1.9.1
Fluent-plugin-rewrite-tag-filter:2.2.0

2020-06-09 09:20:08 +0000 [info]: fluent/log.rb:322:info: gem 'fluentd' version '1.9.1'
2020-06-09 09:20:08 +0000 [trace]: fluent/log.rb:281:trace: registered output plugin 'rewrite_tag_filter'
/usr/local/lib/ruby/gems/2.6.0/gems/fluent-plugin-rewrite-tag-filter-2.3.0/lib/fluent/plugin/out_rewrite_tag_filter.rb:38:in ``': No such file or directory - hostname (Errno::ENOENT)
	from /usr/local/lib/ruby/gems/2.6.0/gems/fluent-plugin-rewrite-tag-filter-2.3.0/lib/fluent/plugin/out_rewrite_tag_filter.rb:38:in `configure'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.9.1/lib/fluent/plugin.rb:173:in `configure'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.9.1/lib/fluent/agent.rb:132:in `add_match'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.9.1/lib/fluent/agent.rb:74:in `block in configure'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.9.1/lib/fluent/agent.rb:64:in `each'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.9.1/lib/fluent/agent.rb:64:in `configure'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.9.1/lib/fluent/root_agent.rb:146:in `configure'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.9.1/lib/fluent/engine.rb:105:in `configure'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.9.1/lib/fluent/engine.rb:80:in `run_configure'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.9.1/lib/fluent/supervisor.rb:541:in `run_supervisor'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.9.1/lib/fluent/command/fluentd.rb:330:in `<top (required)>'
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.9.1/bin/fluentd:8:in `<top (required)>'
	from /usr/local/bin/fluentd:23:in `load'
	from /usr/local/bin/fluentd:23:in `<main>'

Looks like it is failing on 

    @hostname = `#{@hostname_command}`.chomp

**Comment by repeatedly** [comment]
Change `hostname_command` parameter to proper command if your OS doesn't support `hostname` command: https://github.com/fluent/fluent-plugin-rewrite-tag-filter#configuration

**Comment by dimalbaby** [comment]
@repeatedly This is missing on the based os.  Thanks for your quick response. closing the ticket

**Comment by spijet** [comment]
I faced a similar issue on (Alpine-based) `fluentd/fluentd-v1.16-1` Docker image, even though there *is* a `hostname` command available in `$PATH`:

```
/ $ which hostname
/bin/hostname
/ $ hostname -s
9041d28a1ae5
/ $ env | grep PATH
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

For now I specify `hostname_command /bin/hostname` in every instance of the plugin's config, which *kinda* solves this issue.
