### ISSUE TITLE
Example config not working

### ISSUE THREAD

**Issue by harryge00** [fluent/fluent-plugin-rewrite-tag-filter#103]
I tried to follow  https://docs.fluentd.org/output/rewrite_tag_filter#example 
```
<source>
  @type dummy
  dummy {"message":"[info]: abc def ghi xxx"} 
  tag app.component
  auto_increment_key seq
</source>

<match app.component>
  @type rewrite_tag_filter
  <rule>
    key message
    pattern /^(w+)$/
    tag $1.${tag}
  </rule>
</match>

<match **>
  @type stdout
</match>
```
However, it produces no output. Fluentd version: 1.3.2,  'fluent-plugin-rewrite-tag-filter' version '2.3.0'.

**Comment by okkez** [comment]
Try `pattern /^\[(\w+)\]/`.
You can debug this configuration with `fluentd -c fluent.conf -vvv`.

**Comment by okkez** [comment]
You can report the issue to https://github.com/fluent/fluentd-docs-gitbook about docs example.
