### ISSUE TITLE
Unexpected behavior - events lost when no rule matches or no explicit tag rewrite

### ISSUE THREAD

**Issue by tumbl3w33d** [fluent/fluent-plugin-rewrite-tag-filter#115]
I've used this plugin for the first time and was surprised by the behavior, that, if no rule matches, the event is lost and not re-emitted unchanged. Maybe I have missed it in the docs or misunderstood some of it, so I'd like to show what I've done to get some feedback on it:

**First approach** - only in case the `source` field has the value `stderr`, rewrite the tag
```
<match docker.*.*-accesslogs>
  @type rewrite_tag_filter
  <rule>
    key source
    pattern /^stderr$/
    tag haproxy-stderr
  </rule>
</match>
```
**Expected**: matched events to be retagged, unmatched events to be left untouched but kept in the processing chain (I think fluentd calls this re-routed).
**Actual**: events that didn't match the single rule are gone.

**Secong approach** - the same, but let's be explicit about keeping the other events with same tag
```
<match docker.*.*-accesslogs>
  @type rewrite_tag_filter
  <rule>
    key source
    pattern /^stderr$/
    tag haproxy-stderr
  </rule>
  <rule>
    key source
    pattern /^stdout$/
    tag ${tag}
  </rule>
</match>
```
**Expected**: effectively, as above
**Actual**: as above

**Third approach** - the same, but explicitly rewrite to some other tag that I would also handle in the rest of the processing chain
```
<match docker.*.*-accesslogs>
  @type rewrite_tag_filter
  <rule>
    key source
    pattern /^stderr$/
    tag haproxy-stderr
  </rule>
  <rule>
    key source
    pattern /^stdout$/
    tag ${tag}-stdout
  </rule>
</match>
```
Works as expected, but feels unnecessary. I would expect either a documentation hint that my ruleset must cover all possible cases (and that I MUST rewrite the tag to not lose the event) or (preferred) some config flag like "re-emit unmatched".

Looking forward to your answers and thanks in advance!

**Comment by y-ken** [comment]
Hi all. Sorry for late replying.
If there is no match and this passes through with the same tag, it will match again with the same pattern and pass through processing will be performed by rewrite-tag-filter. This will cause an infinite loop.

I believe that if we write the same match rule, only the first one will be processed and the second one will not be reached.
This is because by re-emiting, the tag matching evaluation will start from the beginning of the config.

```
# This is the sample with enabling passthrough. but it won't process last part of output to s3 from my understanding.
<match docker.*.*-accesslogs>
  @type rewrite_tag_filter
  <rule>
    key source
    pattern /^stderr$/
    tag haproxy-stderr
  </rule>
  <rule>
    key source
    pattern /^stdout$/
    tag ${tag}-stdout
  </rule>
  <rule>
    key source
    pattern /.+/
    tag ${tag}
  </rule>
</match>

# some output process
<match docker.*.*-accesslogs>
  type s3
</match>
```

**Comment by y-ken** [comment]
Thank you for feedback. I have updated README to clarify the catch-all necessity.
https://github.com/fluent/fluent-plugin-rewrite-tag-filter/commit/86a7a2d8da74894f0142320af9f993b5bf55f9bb
