### ISSUE TITLE
Impossible to use nested attributes

### ISSUE THREAD

**Issue by quasipedia** [fluent/fluent-plugin-rewrite-tag-filter#13]
Unless there's some specific syntax that I missed finding in the documentation, the plugin does not work with an `<attribute>` that is not a flat, first-level one.

For example, the following rule (written for an event in which the `geoip` object contains various data such as `country`, `region`, `latitude`, etc...)  fails to execute correctly:

```
<match geoip.** >
  type               rewrite_tag_filter
  rewriterule1       geoip.country SWE lookup.${tag}
  rewriterule2       geoip.country [^SWE] ready.${tag}
</match>
```

Resulting in the entire entry being lost.  Am I doing something wrong?

**Comment by stensonb** [comment]
I'd love a solution too (my use case: https://groups.google.com/forum/#!topic/fluentd/ncW-fEGBfko)

**Comment by repeatedly** [comment]
@y-ken how about this?

**Comment by zacharynevin** [comment]
I got around this by using the `record_transformer` plugin to take the nested key to the top-level, and then applying the tag.

For example, imagine that you have a kubernetes cluster with environments (test, staging, prod) segregated by namespace:

```
<filter kubernetes.**>
  type kubernetes_metadata
</filter>

<filter kubernetes.**>
  type record_transformer
  enable_ruby
  <record>
    environment "${kubernetes[\"namespace_name\"]}"
  </record>
</filter>

<match kubernetes.**>
  @type rewrite_tag_filter
  rewriterule1 environment ^.+$ $1.${tag}
</match>

<filter kubernetes.**>
  @type record_transformer
  remove_keys environment
</filter>
```

**Comment by kushwiz** [comment]
@zacharynevin  Thanks!

**Comment by dhawal55** [comment]
@zacharynevin I'm using the same example as yours but in my case `$1` is not getting substituted by environment value. It is always empty. What am I doing wrong??

```
<filter kubernetes.**>
    type record_transformer
    enable_ruby 
    <record>
      namespace ${kubernetes["namespace_name"]}
    </record>
  </filter>
  
<match kubernetes.**>
    @type rewrite_tag_filter
    rewriterule1 namespace .+ $1.${tag}
  </match>
```

I end up with tag values as `.kubernetes.var.log...`

**Comment by chancez** [comment]
Oh man I spent so much time trying to debug this, I'm so glad I found this. This is definitely a really big pain point that I'm sure many people will run into. I'm also using Kubernetes, so this is where I ran into the problem as well.

**Comment by y-ken** [comment]
I'm glad to see this. Can you give me the input samples?

**Comment by chancez** [comment]
@y-ken do you mean an example of a record field? It's basically any record field which is nested.

ie:

```
{
  "kubernetes": {
    "namespace_name": "default"
  }
}
```

Where the rewrite rule `kubernetes.namespace_name` doesn't work, because that's not a valid way to access an object's nested attribute in ruby. 

This line is the problem area: https://github.com/fluent/fluent-plugin-rewrite-tag-filter/blob/master/lib/fluent/plugin/out_rewrite_tag_filter.rb#L84

`rewritekey` is "kubernetes.namespace_name" from the rewrite rule config.
`rewritevalue` is "" because we actually need `record["kubernetes"]["namespace_name"]`. I think a solution is the following:

Change the above line to this:
```
rewritevalue = rewritekey.split(".").inject(record) { |hash, key| hash[key] }.to_s
```

This of course, would make it impossible to use a field which has a literal dot in it (non-nested field), so perhaps this could be a configurable option. Like this:

```
if @enable_dot_access_nested_fields # probably should pick a better config option name
  rewritevalue = rewritekey.split(".").inject(record) { |hash, key| hash[key] }.to_s
else
  rewritevalue = record[rewritekey].to_s
end
```

I'm considering opening a PR to fix this, what do you think about the available options @y-ken? Maybe there's a way to get full access to ruby when trying to access fields, similar to how docs.fluentd.org/v0.12/articles/filter_record_transformer works with `enable_ruby` and supports using `${record["foo"]["bar"]}` syntax.

**Comment by chancez** [comment]
For what it's worth, this is what I ended up with in my config in order to work around it. It's based on @dhawal55's setup:

```
# rewrite_tag_filter does not support nested fields like
# kubernetes.container_name, so this exists to flatten the fields
# so we can use them in our rewrite_tag_filter
<filter kubernetes.**>
  @type record_transformer
  enable_ruby true
  <record>
    kubernetes_namespace_container_name ${record["kubernetes"]["namespace_name"]}.${record["kubernetes"]["container_name"]}
  </record>
</filter>

# retag based on the container name of the log message
<match kubernetes.**>
  @type rewrite_tag_filter
  rewriterule1 kubernetes_namespace_container_name  ^(.+)$ kube.$1
</match>

# Remove the unnecessary field as the information is already available on
# other fields.
<filter kube.**>
  @type record_transformer
  remove_keys kubernetes_namespace_container_name
</filter>
```

The more comlete snippet that uses that tag for parsing kubernetes logs is here: https://gist.github.com/chancez/b79f7c1d94008eb46ad949480c85fe97.

**Comment by y-ken** [comment]
Starting discussion to access nested data as standard syntax
https://github.com/fluent/fluentd/issues/1578

**Comment by chancez** [comment]
The upstream changes have landed in https://github.com/fluent/fluentd/pull/1637 to make this possible via a re-usable helper that plugins can use.

**Comment by y-ken** [comment]
@okkez 
Cloud you please support nested attribute?
I'd like to use fluentd core helper. At least, It should be keep same setting style

**Comment by okkez** [comment]
OK, I will take time on this issue later.
