### ISSUE TITLE
Cannot install via fluent-gem

### ISSUE THREAD

**Issue by moebiuseye** [fluent/fluent-plugin-rewrite-tag-filter#20]
I've tried to install this plugin using fluent-gem and it fails. 

Here's the mlmf.log file:

```
"gcc -o conftest -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.    -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -mtune=generic -fPIC conftest.c  -L. -L/usr/lib64 -L. -Wl,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic  -m64   -lruby  -lpthread -lrt -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

I have installed ruby-devel and I have previously installed other plugins with fluentd-gem, 
so I'm assuming this isn't comming from the way I'm doing it, although I could be wrong.

**Comment by y-ken** [comment]
Would you please tell me the further information?

* ruby version
* OS and its version
* have installed gcc?
* if using redhat/centos, copy the result of `getenforce` command. (SELinux check)
* if using debian/ubuntu, have you installed `build-essential` yet?
