### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dwoo4dwoo** [fluent/fluent-plugin-rewrite-tag-filter#21]
Hello,

I was wondering if you were planning a new release sometime soon?  I'm particularly interested in https://github.com/fluent/fluent-plugin-rewrite-tag-filter/pull/14 ... and it'd be nice to avoid having to individually patch files.

Thank you ... David

**Comment by y-ken** [comment]
Sure! Wait a moment please.

**Comment by y-ken** [comment]
Hi @dwoo4dwoo 
It has released v1.5.2 now! It comes label support.
https://rubygems.org/gems/fluent-plugin-rewrite-tag-filter/versions/1.5.2

**Comment by dwoo4dwoo** [comment]
Awesome - many thanks!!  David
