### ISSUE TITLE
Rewrite Tag Match cannot be first in config?

### ISSUE THREAD

**Issue by thekantian** [fluent/fluent-plugin-rewrite-tag-filter#25]
I've installed td-agent via the Treasure Data toolbelt just now on latest ubuntu trusty.

I have a config file like:

```
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>
<match **>
  @type rewrite_tag_filter
  rewriterule1 event ^foo1$ prefix.suffix1
  rewriterule2 event ^foo2$ prefix.suffix2
</match>
<match prefix.*>
  @type stdout
</match>
```

When I run this config, I do not get the expected output in stdout. If I add this before the rewrite match, I do get the expected output:

```
<filter **>
  type stdout
</filter>
```

Is this a known issue? If so, any ideas for workarounds?

**Comment by repeatedly** [comment]
Known issue. See the official document: http://docs.fluentd.org/articles/config-file#match-order

**Comment by thekantian** [comment]
I'm not sure that is my issue @repeatedly (thanks for the quick response!).

I want the ** match to be a black hole at the first step, and only my rewritten tags to emerge. The issue here would be more with the rewrite plugin depending on some state change made by a previous match from the forward input which is missing when the rewrite plugin is first in the file...

**Comment by y-ken** [comment]
Hi

How about putting catch-all block at te top with out_copy?
http://docs.fluentd.org/articles/out_copy

```
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

<match **>
  @type copy
  <store>
  @type rewrite_tag_filter
  rewriterule1 event ^foo1$ prefix.suffix1
  rewriterule2 event ^foo2$ prefix.suffix2
  </store>
  <store>
  # put another setting here
  </store>
</match>

<match prefix.*>
  @type stdout
</match>
```

Or, do you need filter version of rewrite_tag_filter?

**Comment by repeatedly** [comment]
I'm not sure your final data flow but <match **> on the top seems bad.
So organizing tag and match / label routing is better for maintaing data flow.

**Comment by thekantian** [comment]
@y-ken I've tried:

```
<match **>
  @type copy
  <store>
  @type rewrite_tag_filter
  rewriterule1 event ^foo1$ prefix.suffix1
  rewriterule2 event ^foo2$ prefix.suffix2
  </store>
  <store>
    @type null
  </store>
</match>
```

And it still does not produce the expected output of re-tagged events.

@repeatedly this is a multi-step pipeline that i'm trying to put on separate workers to reduce complexity so I don't think the advice applies to my case here. I can combine this step onto my previous one but it seems odd to me that the forward input does not work as expected to compose a pipeline.

Thanks so much for the help guys - for now I will combine this into my previous step and see if I can get it to work while I understand what the best way forward is. I am new to the fluentd ecosystem.

**Comment by geek876** [comment]
I am trying to do similar thing but having issues. My use-case is:

On my forwarder

```
<source>
  type tail
  format apache
  path /var/log/apache2/access.log
  tag apache_access
</source>

<source>
  type syslog
  ..
  tag syslog
</source>

<filter apache_access.**>
  @type record_transformer
  <record>
    hostname "#{Socket.gethostname}"
  </record>
  <record>
    service apache
  </record>
  <record>
    tag ${tag}
  </record>
  <record>
    output file
  </record>
</filter>

<filter syslog.**>
  @type record_transformer
  <record>
    hostname "#{Socket.gethostname}"
  </record>
  <record>
    service syslog
  </record>
  <record>
    tag ${tag}
  </record>
  <record>
    output s3
  </record>
</filter>

<match *.**>
  type forward
  <server>
    host 192.168.30.10
  </server>
</match>
```
On my Aggregator
```
<match *.**>
  @type rewrite_tag_filter
  rewriterule1 output ^file$ file
  rewriterule2 output ^s3$  s3
</match>

<match file.**>
  type file
  path /tmp/fluentd.log
</match>

<match s3.**>
...
</match>

```

So at forwarder level, I simply add a field `output` indicating which output stream the log should end up on, makes the forwarder config very slim. Then, at aggregator level, I want to re-tag looking at the `output` field and then match it specifically. 

This will require the `catch-all` match to be first in the list, which is not possible.

Any thoughts ?

**Comment by repeatedly** [comment]
> This will require the catch-all match to be first in the list, which is not possible.

Putting `<match *.**>` to the bottom seems to resolve the problem.
Is this a problem?

**Comment by geek876** [comment]
@repeatedly: Yes it will work technically but then I won't be able to match `file` or `s3` (i think). The purpose of catch-all is to re-tag based on the `output` and then filter them .
