### ISSUE TITLE
Can't install on fluent/fluentd-docker-image

### ISSUE THREAD

**Issue by dgarros** [fluent/fluent-plugin-rewrite-tag-filter#27]
Hi 

I'm facing an issue while trying to install this plugin in the official docker image fluent/fluentd-docker-image
I'm using version : fluent/fluentd:v0.12.24 

Apparently it's related to a dependency "string-scrub" that has strict dependencies on Ruby version

```
Step 13 : RUN gem install --no-ri --no-rdoc fluent-plugin-newsyslog                   fluent-plugin-rewrite-tag-filter
 ---> Running in 83d42af2e87a
ERROR:  Error installing fluent-plugin-rewrite-tag-filter:
	string-scrub requires Ruby version < 2.1, >= 1.9.3.
```

Any idea how I can solve that ? My end goal is that I'd like to be able to rewrite tags on the fly
Thanks
Damien

**Comment by repeatedly** [comment]
This has already resolved the master.

@y-ken please release new version ASAP.

**Comment by repeatedly** [comment]
And add me to gem owner.

**Comment by y-ken** [comment]
@dgarros @repeatedly 
I've released v1.5.5 now. Please check it with this version. Thank you.
https://rubygems.org/gems/fluent-plugin-rewrite-tag-filter/versions/1.5.5

**Comment by y-ken** [comment]
@repeatedly 
I have also added owner of this gem.

**Comment by repeatedly** [comment]
@y-ken Thanks for quick work!

**Comment by dgarros** [comment]
Thanks for the quick fix, I can install it now
Thanks a lot
