### ISSUE TITLE
Wildcard for multiple tags does not work with rewrite-tag-filter

### ISSUE THREAD

**Issue by martinhynar** [fluent/fluent-plugin-rewrite-tag-filter#32]
Hi, I have this simple configuration where I use single tag in source. After that, first match that applies rewrite_tag_filter does not work and swallows all events when `**` pattern is used.

See the config
```
<source>
  @type dummy
  dummy {"message" : "event from alpha service", "service" : "alpha"}
  tag dummy
  auto_increment_key seq
</source>

# REF1
# Here, ** makes all events to disappear
<match **>
  @type rewrite_tag_filter
  rewriterule1 service ^(alpha)$ service.$1
  rewriterule2 service .+ unmatched
</match>

<match **>
  @type file
  path outfile
  append true
  time_slice_format %Y%m%d
  time_slice_wait 10m
  time_format %Y%m%dT%H%M%S%z
  buffer_type memory
  flush_interval 3s
</match>
```

Changing `**` at `REF1` to 
1. `dummy` makes the events pass through the filter where tag is transformed to `service.alpha`
1. `dummy.*` makes the events not match the pattern and preserving `dummy` tag

Both these changes make events to appear in out file.
Only when `**` is kept at `REF1`, events disappear.
The `**` for file output works just fine.

**Comment by repeatedly** [comment]
See: http://docs.fluentd.org/v0.12/articles/config-file#match-order

**Comment by repeatedly** [comment]
This is fluentd routing spec, not rewrite-tag-filter issue.

**Comment by martinhynar** [comment]
Then this description from rewrite-tag-filter is bit confusing, or perhaps ambiguous: _Re-emit the record with rewrited tag when a value matches/unmatches with a regular expression._. This description made me think that match pattern for rewrite-tag-filter will let certain events pass into the rewrite-tag-filter and will be re-emitted to subsequent matches. But now if I understand that correctly, the re-emitted event is passed to all match elements again, right? This is, the re-emitted event is again matched by `**` and circulates infinitely, right?

**Comment by repeatedly** [comment]
> But now if I understand that correctly, the re-emitted event is passed to all match elements again, right?

right.
