### ISSUE TITLE
Support for 0.14?

### ISSUE THREAD

**Issue by bryanlarsen** [fluent/fluent-plugin-rewrite-tag-filter#35]
1.5.6 specifically excludes fluent 0.14 in the gemspec.   1.5.5 appears to work for me with fluentd 0.14, although my usage is probably far from a complete test case.   Is there a release planned with 0.14 support?

**Comment by bryanlarsen** [comment]
Never mind, it's in #30.   I swear I searched for it.  Sorry about that.

**Comment by y-ken** [comment]
I'd like to make a time for this month. Thank you.
