### ISSUE TITLE
Support section notation

### ISSUE THREAD

**Issue by okkez** [fluent/fluent-plugin-rewrite-tag-filter#41]
How about section notation like this?

```
<match **>
  @type rewrite_tag_filter
  <rule>
    key domain
    pattern ^(mail)\.(example)\.com$
    tag rewrited.${tag}.$2$1
  </rule>
</match>
```

**Comment by y-ken** [comment]
it seems very good!
i'd like to enable this style for v0.12 too.

2017/10/13 12:58 "okkez" <notifications@github.com>:

**Comment by okkez** [comment]
OK, I will try to implement this style for master and then backport the feature if I can.
