### ISSUE TITLE
Unable to keep old tags on some messages

### ISSUE THREAD

**Issue by Verhaeg** [fluent/fluent-plugin-rewrite-tag-filter#50]
Hi.. I'm trying to use this plugin to change the tag for only a few messages that match a certain condition and keep the other messages as they came.

my configuration is something like:
```
<filter kubernetes.var.log.containers.app**>
  @type record_transformer
  enable_ruby
  <record>
    custom_conditional ${record["field"].eql?("some value to match");}
  </record>
</filter>

<match kubernetes.var.log.containers.app**>
  @type rewrite_tag_filter
  rewriterule1 custom_conditional "true" new.tag
  rewriterule2 custom_conditional "false" ${tag} # Tried without this line as well
</match>

#... Some other processing

<match new.**>
...
</match>
<match kubernetes.**>
...
</match>
```

So if I have the following logs:
```
{"field":"some value to match", "fieldA":"foo", "foo":"bar"}
{"field":"some other value", "foo":"bar"}
```

I want the first one to have *new.tag* and the other one to keep the original tag from Kubernetes
But what happens is that new.tag is applied but the other message is lost... nowhere to be found =/

thanks for any help

**Comment by okkez** [comment]
`@type rewrite_tag_filter` re-emit events that are rewritten tag.

Try following:

```
<match kubernetes.var.log.containers.app**>
  @type rewrite_tag_filter
  rewriterule1 custom_conditional true matched.${tag}
  rewriterule2 custom_conditional false unmatched.${tag}
</match>

<match matched.**>
  ...
</match>
<match unmatched.**>
  ...
</match>
```

**Comment by Verhaeg** [comment]
Hi @okkez 
thanks for the response, it worked perfectly, I just added some comments to the configuration to let others developers know about the change.

Thanks for the help
