### ISSUE TITLE
Question: Is it possible to prefix/append something to the initial tag?

### ISSUE THREAD

**Issue by jmglsn** [fluent/fluent-plugin-rewrite-tag-filter#57]
Hi,
first of all thank you for this plugin, makes live much easier!

In my current setup I'm in a situation where it would be helpful to rewrite the tag in a way that my change is placed before/after the current tag. Because the tag itself is somehow dynamic.

Imagine you have a larger set of services (containers) running and you now want to inspect the output of those containers in a more generic way.

So is it possible to do something like this?
```conf
  rewriterule1 log ^nginx.* ${tag}.nginx
  rewriterule2 log .+ ${tag}.app
```

If the initial tag is dynamic we could just add a suffix to it. So out of `myservice-a` we could create `myservice-a.nginx` if the log itself is nginx based and we would go for `myservice-a.app` as a fallback. This could be applied to a larger set of services, keeping original part of the service tag, but make it more expressive.
Thanks in advance!

**Comment by okkez** [comment]
Yes. See [Usage](https://github.com/fluent/fluent-plugin-rewrite-tag-filter#usage) section in README.md.

Example1: if incoming events have common prefix

```
<source>
  @type forward
</source>

<match prefix.*>
  @type rewrite_tag_filter
  <rule>
    key log
    pattern ^nginx$
    tag rewritten.${tag_parts[1]}.nginx
  </rule>
  <rule>
    key log
    pattern ^.+$
    tag rewritten.${tag_parts[1]}.app
  </rule>
</match>

<match rewritten.**>
   @type stdout
</match>
```

Example2: incoming events don't have common prefix

```
<source>
  @type forward
  @label @INPUT
</source>

<label @INPUT>
  <match **>
    @type rewrite_tag_filter
    <rule>
      key log
      pattern ^nginx$
      tag ${tag}.nginx
    </rule>
    <rule>
      key log
      pattern ^.+$
      tag ${tag}.app
    </rule>
    @label @OUTPUT
  </match>  
</label>

<label @OUTPUT>
  <match **.nginx>
     @type stdout
  </match>
  <match **.app>
    @type null
  </match>
</label>
```

See also #53

**Comment by jmglsn** [comment]
@okkez Thank you, I didn't realize this when I checked the readme.
