### ISSUE TITLE
rewrite-tag-filter events not re-emitted with fluentd-kubernetes-daemonset

### ISSUE THREAD

**Issue by trevex** [fluent/fluent-plugin-rewrite-tag-filter#59]
I am struggling to get the the `rewrite-tag-filter` to work with [fluentd-kubernetes-daemonset](https://github.com/fluent/fluentd-kubernetes-daemonset).

This is the basic config used:
```
    @include kubernetes.conf

    <match kubernetes.**>
      @type copy
      <store>
        @type rewrite_tag_filter
        remove_tag_prefix kubernetes
        <rule>
          key kubernetes.namespace_name
          pattern ^(.+)$
          tag namespace.$1.${tag}
        </rule>
      </store>     
      <store>
        @type file
        path /var/log/fluent/test
      </store>
    </match>

    <match namespace.**>
      @type copy
      <store>
        @type forward
        send_timeout 60s
        recover_wait 10s
        hard_timeout 60s
        dns_round_robin true
        <server>
          name fluentd-aggregator-service
          host "#{ENV['FLUENT_AGGREGATOR_HOST']}"
          port "#{ENV['FLUENT_AGGREGATOR_PORT']}"
        </server>
      </store>
      <store>
        @type stdout
      </store>
    </match>
```
All events can be found in `/var/log/fluent/test`, but the rewrite is either unsuccessful or does not happen. I previously tried `rewriterule1 $.kubernetes.namespace_name ^(.+)$ namespace.$1.${tag}` unsuccessfully as well.

Interestlingly adding the following at the bottom does not print anything to `stdout`:
```
    <match **>
      @type stdout
    </match>
```

I am struggling to see anything wrong with the above configuration. Help would very much be appreciated.

As reference the included [kubernetes.conf](https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v0.12/debian-elasticsearch/conf/kubernetes.conf), [Dockerfile](https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v0.12/debian-elasticsearch/Dockerfile) of fluentd-kubernetes-daemonset and its [entrypoint.sh](https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v0.12/debian-elasticsearch/entrypoint.sh).

**Comment by okkez** [comment]
Could you show me your logs from k8s?
If you want to use nested attributes see https://github.com/fluent/fluent-plugin-rewrite-tag-filter/tree/fluentd-v0.12#nested-attributes

**Comment by trevex** [comment]
Thank you very much, I thought the nested-attributes were backported. I updated the configuration file following your documentation and it works.

One minor change I had to do is change the `record_transformer` field name from `namespace` to `namespace_name`:
```
<filter kubernetes.**>
  @type record_transformer
  enable_ruby
  <record>
    kubernetes_namespace ${record["kubernetes"]["namespace_name"]}
  </record>
</filter>
```

Thank you for the quick help :+1:
