### ISSUE TITLE
after rewrite-tag, nothing  output

### ISSUE THREAD

**Issue by pangxudong** [fluent/fluent-plugin-rewrite-tag-filter#64]
After I added the match typed 'rewrite_tag_filter', nothing output. before added the section, everyting works very well. this is my fluent.conf:

```

<match fluent.**>
  @type null
</match>

<source>
  @type tail
  path /var/log/containers/*.log
  pos_file /pos/containers.pos
  time_key time
  time_format %Y-%m-%dT%H:%M:%S.%NZ
  tag kubernetes.*
  format json
  read_from_head true
</source>

<filter kubernetes.**>
  @type kubernetes_metadata
  merge_json_log true
  preserve_json_log true
</filter>

<match kubernetes.**>
  @type rewrite_tag_filter
  <rule>
    key $.kubernetes.namespace_name
    pattern ^(.+)$
    tag $1.${tag}
  </rule>
</match>

<match **>
   @type stdout
</match>

```

**Comment by repeatedly** [comment]
What is the `kubernetes.namespace_name` value?

**Comment by pangxudong** [comment]
each namespaces of k8s. this is a raw message: 

`{
"log":"E0320 01:48:12.084444 1 reflector.go:201] k8s.io/kube-state-metrics/collectors/statefulset.go:68: Failed to list *v1beta1.StatefulSet: statefulsets.apps is forbidden: User \"system:serviceaccount:monitoring:kube-state-metrics\" cannot list statefulsets.apps at the cluster scope\n",
"stream":"stderr",
"docker":{
"container_id":"3ad9d3aaca495960302762aa48aaa570ee3888402fa1b293cdb20843b334d38a"
},
"kubernetes":{
"namespace_name":"monitoring",
"pod_id":"55a4e0fc-268d-11e8-9300-00163e0ca638",
"pod_name":"kube-state-metrics-5cbc9c4c9c-t2w9p",
"container_name":"kube-state-metrics",
"labels":{
"app":"kube-state-metrics",
"pod-template-hash":"1767570757"
},
"host":"10.104.7.51"
}
}`

**Comment by pangxudong** [comment]
I copied the config example  of [https://github.com/fluent/fluent-plugin-rewrite-tag-filter#nested-attributes](url), but it doesn't work.

**Comment by okkez** [comment]
Could you show me your version of fluentd and plugins?
If you use Fluentd v0.12.x and fluent-plugin-rewrite-tag-filter v1.x, see https://github.com/fluent/fluent-plugin-rewrite-tag-filter/tree/fluentd-v0.12#nested-attributes

**Comment by pangxudong** [comment]
@okkez  this is my fluentd Dockerfile:

```
FROM fluent/fluentd:v0.14-debian
MAINTAINER Joakim Karlsson <joakim@roffe.nu>

RUN apt-get update \
 && apt-get upgrade -y \
 && apt-get install -y --no-install-recommends \
            ca-certificates \
            ruby \
 && buildDeps=" \
      make gcc g++ libc-dev \
      ruby-dev \
      wget bzip2 gnupg dirmngr \
    " \
 && apt-get install -y --no-install-recommends $buildDeps \
 && update-ca-certificates \
 && echo 'gem: --no-document' >> /etc/gemrc \
 && gem install fluent-plugin-kubernetes_metadata_filter_v0.14 -v 0.24.1 \
 && gem install fluent-plugin-rewrite-tag-filter -v 1.6.0 \
 && gem install gelf -v 3.0.0 \
 && gem install fluent-plugin-systemd -v 0.3.0 \
 && wget https://raw.githubusercontent.com/bedag/fluent-plugin-gelf/master/lib/fluent/plugin/out_gelf.rb -O /fluentd/plugins/out_gelf.rb \
 && apt-get purge -y --auto-remove \
                  -o APT::AutoRemove::RecommendsImportant=false \
                  $buildDeps \
 && rm -rf /var/lib/apt/lists/* \
 && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

ENTRYPOINT ["gosu"]

CMD ["root", "fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins"]
```

**Comment by pangxudong** [comment]
@okkez hi, I changed fluentd version to 0.14.25-debian and fluent-plugin-rewrite-tag-filter to 2.0.0，every works ok now, thank you!

**Comment by okkez** [comment]
OK, thanks!

**Comment by repeatedly** [comment]
v0.14.25 is older fluentd. if you don't have any specific reason, please use latest 1.1.2 version.

**Comment by pangxudong** [comment]
@repeatedly thank you, I'll try.
