### ISSUE TITLE
Update configuration examples to latest configuration syntax

### ISSUE THREAD

**Issue by kasiprasad** [fluent/fluent-plugin-rewrite-tag-filter#65]
Was reviewing example.conf and example2.conf but they seem to use the legacy configuration style. Please provide examples using the new configuration style which has rule elements instead of manually named rewriterule_N_

**Comment by y-ken** [comment]
Yes. It need to update. Thank you for reporting!
https://github.com/fluent/fluent-plugin-rewrite-tag-filter/pull/60
