### ISSUE TITLE
Regex patterns are escaped 

### ISSUE THREAD

**Issue by jkawamoto** [fluent/fluent-plugin-rewrite-tag-filter#67]
* fluentd version '1.1.3'
* fluent-plugin-rewrite-tag-filter version '2.0.2'

If I use this rule 

```xml
<rule>
  key source
  pattern /^stdout$/
  tag nginx.access.${tag}
</rule>
```

the regex pattern is escaped like this

```
2018-05-17 23:18:47 +0000 [info]: #0 adding rewrite_tag_filter rule: source [#<Fluent::PluginHelper::RecordAccessor::Accessor:0x0000561936da6d80 @keys="source">, /\/^stdout$\//, "", "nginx.access.${tag}"]
```

and doesn't match "stdout". On the other hand, if I don't enclose the pattern with `/` like this

```xml
<rule>
  key source
  pattern ^stdout$
  tag nginx.access.${tag}
</rule>
```

the pattern is automatically enclosed like this

```
2018-05-17 23:53:56 +0000 [info]: #0 adding rewrite_tag_filter rule: source [#<Fluent::PluginHelper::RecordAccessor::Accessor:0x000055cfc9b5c1d0 @keys="source">, /^stdout$/, "", "nginx.access.${tag}"]
```

and works as expected.

According to the following explanation in README.md

> pattern (regexp) (required): The regular expression. /regexp/ is preferred because /regexp/ style can support character classes such as /[a-z]/. The pattern without slashes will cause errors if you use patterns start with character classes.

this behaviour seems not to be intended.

**Comment by okkez** [comment]
It's expected behavior.
fluent-plugin-rewrite-tag-filter v2.0.2 does not support ``pattern /^stdout$/``.

**Comment by jkawamoto** [comment]
In that case, README.md should be modified since all rules in the usage have "/".

**Comment by okkez** [comment]
You must refer [the README.md according to the version you installed](https://github.com/fluent/fluent-plugin-rewrite-tag-filter/tree/v2.0.2).
Because the master branch is in developing and not stable.

**Comment by jkawamoto** [comment]
Ahh, I see. I think it’d be better the readme has a link to the current version’s one since it’s confusing. Anyway, I’ll close this issue. 

Thanks for your help.
