### ISSUE TITLE
Can i rewrite tag by key=tag

### ISSUE THREAD

**Issue by Renz2018** [fluent/fluent-plugin-rewrite-tag-filter#70]
for example
input tag: aa-bb-cc
i want to rewrite tag to cc.bb.aa
but i use key tag, i dosen't work
the key is only use in message???

\<match aa-bb-cc\>
@type rewrite_tag_filter
\<rule\>
key tag
pattern (.+)-(.+)-(.+)
tag $3.$2.$1
\</rule\>
\</match\>

**Comment by okkez** [comment]
You need to add a tag field which includes tag value.
How about followings?

```
<source>
  @type dummy
  tag aa-bb-cc
  @label @INPUT
</source>

<label @INPUT>
  <filter>
    @type record_transformer
    <record>
      tag ${tag}
    </record>
  </filter>
  <match aa-bb-cc>
    @type rewrite_tag_filter
    <rule>
      key     tag
      pattern /(.+)-(.+)-(.+)/
      tag     $1.$2.$3
    </rule>
    @label @OUTPUT
  </match>
</label>

<label @OUTPUT>
  <match>
    @type stdout
  </match>
</label>
```

**Comment by vanke-renzhe** [comment]
Thanks very much!

**Comment by vanke-renzhe** [comment]
@okkez excuse me,   how can i save the old tag?
`
<label @INPUT>
  <filter>
    @type record_transformer
    <record>
      raw_tag ${tag}
    </record>
  </filter>
  <match aa-bb-cc>
    @type rewrite_tag_filter
    <rule>
      key     tag
      pattern /(.+)-(.+)-(.+)/
      tag     $1.$2.$3
    </rule>
    @label @OUTPUT
  </match>
</label>
`

I use the raw_tag to store old_tag, but if I rewrite tag  in the follow section,
finally I found raw_tag is the modify tag, Is there have method to store old tag?

**Comment by okkez** [comment]
Use `raw_tag` in the rule section like following:

```
    <rule>
      key     raw_tag
      pattern /(.+)-(.+)-(.+)/
      tag     $1.$2.$3
    </rule>
```

**Comment by vanke-renzhe** [comment]
@okkez  I am sorry , I write wrong.
I use the raw_tag in my config,
but finaly I found the raw_tag and tag both are the new_tag
Is the ${tag} placeholder is Lazy Evaluation?? 
I want keep old tag and new tag
Is there have method to store old tag?

**Comment by okkez** [comment]
Could you show me full configuration and sample input, actual output and expected output?
In my local environment, I can keep both old tag (in the record) and new tag.

```
```

**Comment by okkez** [comment]
No response.
