### ISSUE TITLE
Records are dropped silently if tag is not changed / regex doesn't match

### ISSUE THREAD

**Issue by ferbar** [fluent/fluent-plugin-rewrite-tag-filter#73]
A log.warn("rewrite_tag_filter: record dropped") would help here before the next:

https://github.com/fluent/fluent-plugin-rewrite-tag-filter/blob/master/lib/fluent/plugin/out_rewrite_tag_filter.rb#L72

**Comment by okkez** [comment]
@ferbar Could you check #74 ?

**Comment by okkez** [comment]
The default log level is too verbose for this purpose.
And it will cause performance issue.

**Comment by cristifalcas** [comment]
There is any possibility to let unmatched tags to pass to next rules?
