### ISSUE TITLE
Support re-emit event stream

### ISSUE THREAD

**Issue by devin-hpcnt** [fluent/fluent-plugin-rewrite-tag-filter#80]
Hello. I experienced this issue: https://github.com/fluent/fluentd/issues/2153
According to this comment (https://github.com/fluent/fluentd/issues/2153#issuecomment-433780391), this issue will be gone if event stream re-emission is supported. But I think this is difficult to implement due to various tag rewriting situation. Then should something be fixed on fluent 1.x core or just can fixed by only updating this plugin?

**Comment by okkez** [comment]
Could you try #81?

**Comment by devin-hpcnt** [comment]
Okay, I'll try it.

**Comment by devin-hpcnt** [comment]
@okkez It works well at least in my configuration. After applying this patch, the problem is gone. Thank you for your quick patch!

**Comment by okkez** [comment]
Thank you for confirmation.

**Comment by okkez** [comment]
Released v2.2.0.
