### ISSUE TITLE
Cannot set new tag

### ISSUE THREAD

**Issue by iwilltry42** [fluent/fluent-plugin-rewrite-tag-filter#83]
Hey there, I am using `fluent-plugin-rewrite-tag-filter v2.2` with ` fluentd v1.4.2` with the following config:

```
# tag tracebacks
      <match kubernetes.**>
        @type rewrite_tag_filter
        <rule>
          key log
          pattern /^Traceback.+/
          tag ${tag_parts[0]}.traceback
        </rule>
        <rule>
          key log
          pattern /(.+)/
          tag ${tag_parts[0]}.default
        </rule>
      </match>
```

*Problem*: This does not emit any logs.

But if I change the order to e.g. `tag traceback.${tag_parts[0]}`, it works.

Any clue what's happening there?

**Comment by repeatedly** [comment]
Your configuration causes infinite loop. See FAQ: https://docs.fluentd.org/v1.0/articles/out_rewrite_tag_filter#with-rewrite-tag-filter,-logs-are-not-forwarded.-why?

**Comment by iwilltry42** [comment]
Ah, I saw this before, but I didn't really get what causes this problem. 
So the records go through the whole pipeline again after the tag was modified?

**Comment by iwilltry42** [comment]
Anyways, I changed the tag flow up to this point and now it works :)

**Comment by repeatedly** [comment]
> So the records go through the whole pipeline again after the tag was modified?

Technically, new events are emitted. 
This approach reduces copy / paste configuration and users don't need to consider output order on almost cases.
