### ISSUE TITLE
plugin not evaluating tags and re-writing correctly

### ISSUE THREAD

**Issue by Tesseract242** [fluent/fluent-plugin-rewrite-tag-filter#89]
Hi ,

I'm having a problem with this plugin, in that I am using it to evaluate two fields from an incoming exec plugin.
The exec plugin runs an external script which extracts postfix log information and assigns the value of the fields via a regex into multiple keys.
I then have two rules which evaluate the contents of the "from" and "to" keys. 
The problem being is that the first rule is being evaluated correctly and is resulting in the correct output from fluentd. However, the plugin is not evaluating an incoming value that is placed after the first value (in this case key = to). So in this case any e-mails (which are the messages I am evaluating) that match the criteria of the regex  values contained in dog.txt , are not being matched correctly for the second rule.

I have included my config below , if you can help.

Thanks!!

```
<source>
  @type exec
  tag exec_default
  command perl /etc/td-agent/scripts/postfixfluent.pl
  <parse>
    @type regexp
    expression /^(?<date>[A-Za-z]{3}.[0-9]{2}.[0-9]{2}\:[0-9]{2}\:[0-9]{2}).*(?<host>lxmsg\d+v\.nettas\.net).*(?<queueid>[0-9A-Z]{11}).*(?<from>from\=\<.*\>).*(?<to>to\=\<.*\>).*(?<msgid>message\-id\=\<.*\>).*(?<relay>relay\=.*\:\d+).*(?<sendtime>delay\=.*).*(?<delaystat>delays\=.*).*(?<sendstat>status.*)$/
    keys date, host, queueid, from, to, msgid, relay, sendtime, delaystat, sendstat
  </parse>
</source>


<match exec_default.**>
@type rewrite_tag_filter
<rule>
    name        rule_agency_exec_dog_from
    regex_file  /d/d01/logs/emaildomains/dog.txt
    key         from
    tag         ${tag_parts[0]}.matchexec.dog.from
</rule>

<rule>
    name        rule_agency_exec_dog_to
    regex_file  /d/d01/logs/emaildomains/dog.txt
    key         to
    tag         ${tag_parts[0]}.matchexec.dog.to
</rule>
</match>


<match *.matchexec.**>
  @type copy
  <store>
    @type file
    path /d/d01/logs/${tag[0]}/${tag[2]}/${tag[0]}%Y%m%d_%H
    append true
    compress gzip
    symlink_path /d/d01/logs/${tag[0]}/${tag[2]}/current
    slow_flush_log_threshold 60.0
    <format>
      @type csv
      delimiter TAB
      force_quotes False
      fields date, host, queueid, from, to, msgid, relay, sendtime, delaystat, sendstat
      time_type string
      time_format "%F %T %z"
    </format>
    <buffer tag, time>
      @type file
      # write into 1 hour chunks
      timekey 3600
      # wait 10 minutes after each timekey interval before writing it
      timekey_wait 600
      timekey_use_utc False
      #time_slice_format %Y%m%d%H
      path /d/d01/logs/_buffers/exec/${tag[0]}/${tag[2]}
      retry_forever true
      flush_thread_count 6
      flush_mode lazy
    </buffer>
  </store>
```

**Comment by okkez** [comment]
This plugin does not have `regex_file` option.
It seems that you don't use fluent-plugin-rewrite-tag-filter, because your config does not include `<match>` section which has `@type rewrite-tag-filter`.

**Comment by Tesseract242** [comment]
Hi Okkez,

Apologies, I had missed out two lines of config being:

<match exec_default.**>
@type rewrite_tag_filter

The original ruby plugin has been modified to allow reading of regex's from text file.

Apart from that the original plugin is intact.

I have uploaded a copy of this script:

require "fluent/plugin/output"
require "fluent/config/regexp_type"

class Fluent::Plugin::RewriteTagFileFilterOutput < Fluent::Plugin::Output
  Fluent::Plugin.register_output('rewrite_tag_file_filter', self)

  helpers :event_emitter, :record_accessor

  desc 'Capitalize letter for every matched regex backreference.'
  config_param :capitalize_regex_backreference, :bool, :default => false
  desc 'Remove tag prefix for tag placeholder.'
  config_param :remove_tag_prefix, :string, :default => nil
  desc 'Override hostname command for placeholder.'
  config_param :hostname_command, :string, :default => 'hostname'
  desc "The emit mode. If `batch`, this plugin will emit events per rewritten tag."
  config_param :emit_mode, :enum, list: [:record, :batch], default: :batch
  desc 'The fallback tag if there is no match'
  config_param :fallback_tag, :string, :default => nil

  config_section :rule, param_name: :rules, multi: true do
    desc "The name of this rule"
    config_param :name, :string
    desc "The field name to which the regular expression is applied"
    config_param :key, :string
    desc "The path to the file containing regular expressions"
    config_param :regex_file, :string, :default => nil
    desc "The target regex"
    config_param :regex, :regexp, :default => nil
    desc "New tag"
    config_param :tag, :string
    desc "If true, rewrite tag when unmatch pattern"
    config_param :invert, :bool, default: false
  end

  MATCH_OPERATOR_EXCLUDE = '!'

  def configure(conf)
    super

    @rewriterules = []
    rewriterule_names = []
    @hostname = `#{@hostname_command}`.chomp

    @rules.each do |rule|
      unless rule.tag.match(/\$\{tag_parts\[\d\.\.\.?\d\]\}/).nil? or rule.tag.match(/__TAG_PARTS\[\d\.\.\.?\d\]__/).nil?
        raise Fluent::ConfigError, "${tag_parts[n]} and __TAG_PARTS[n]__ placeholder does not support range specify at #{rule}"
      end

      patterns = []

      if rule.regex_file.nil? || rule.regex_file.empty?
        if rule.regex.nil?
          # If the regex file isn't specified we insist the regex argument to be valid
          raise Fluent::ConfigError, "Either regex_file or regex must be specifed for rule '#{rule.name}'"
        else
          # A single regex
          patterns.push(rule.regex)
          log.trace("rewrite_tag_file_filter: rule: #{rule.name} add regex '#{rule.regex}' from inline parameter")
        end
      else
        # Add a file-worth of regex
        File.readlines(rule.regex_file).each do |raw_pattern|
          reg = Fluent::Config.regexp_value(raw_pattern.strip)
          patterns.push(reg)
          log.trace("rewrite_tag_file_filter: File: #{rule.regex_file}: found regex pattern: '#{raw_pattern}'")
        end
      end

      invert = rule.invert ? MATCH_OPERATOR_EXCLUDE : ""
      @rewriterules.push([record_accessor_create(rule.key), patterns, invert, rule.tag])
      rewriterule_names.push(rule.name)
      log.info "rewrite_tag_file_filter: add rule #{rule.name} #{@rewriterules.last}"
    end

    unless @rewriterules.length > 0
      raise Fluent::ConfigError, "missing rewriterules"
    end

    unless @rewriterules.length == rewriterule_names.uniq.length
      raise Fluent::ConfigError, "duplicated rewriterules found #{@rewriterules.inspect}"
    end

    unless @remove_tag_prefix.nil?
      @remove_tag_prefix = /^#{Regexp.escape(@remove_tag_prefix)}\.?/
    end

    @batch_mode = @emit_mode == :batch
  end

  def multi_workers_ready?
    true
  end

  def process(tag, es)
    placeholder = get_placeholder(tag)
    if @batch_mode
      new_event_streams = Hash.new {|h, k| h[k] = Fluent::MultiEventStream.new }
      es.each do |time, record|
        rewrited_tag = rewrite_tag(tag, record, placeholder)
        if rewrited_tag.nil? || tag == rewrited_tag
          log.trace("rewrite_tag_file_filter: tag has not been rewritten", record)
          next
        end
        new_event_streams[rewrited_tag].add(time, record)
      end
      new_event_streams.each do |rewrited_tag, new_es|
        router.emit_stream(rewrited_tag, new_es)
      end
    else
      es.each do |time, record|
        rewrited_tag = rewrite_tag(tag, record, placeholder)
        if rewrited_tag.nil? || tag == rewrited_tag
          log.trace("rewrite_tag_file_filter: tag has not been rewritten", record)
          next
        end
        router.emit(rewrited_tag, time, record)
      end
    end
  end

  def rewrite_tag(tag, record, placeholder)
    @rewriterules.each do |record_accessor, regexes, match_operator, rewritetag|
      # Need to loop over each regex in turn
      rewritevalue = record_accessor.call(record).to_s
      next if rewritevalue.empty? && match_operator != MATCH_OPERATOR_EXCLUDE

      # Inner loop
      regexes.each do |regexp|
        last_match = regexp_last_match(regexp, rewritevalue)
        case match_operator
        when MATCH_OPERATOR_EXCLUDE
          next if last_match
        else
          next if !last_match
          # hoettle: disable backreferences. Not going to entertain them for version 1
          #backreference_table = get_backreference_table(last_match.captures)
          #rewritetag = rewritetag.gsub(/\$\d+/, backreference_table)
        end
        # Aha! We're here! At least one of the regexes for this rule matched!
        #
        # Substitute any placeholders in our rewrite tag
        rewritetag = rewritetag.gsub(/(\${[a-z_]+(\[[0-9]+\])?}|__[A-Z_]+__)/) do
          log.warn "rewrite_tag_file_filter: unknown placeholder found. :placeholder=>#{$1} :tag=>#{tag} :rewritetag=>#{rewritetag}" unless placeholder.include?($1)
          placeholder[$1]
        end
        # And return eagerly since we've found a match.
        return rewritetag
      end ## regexes.each
    end ## @rewriterules.each

    ## If we've got here AND we have a fallback tag, use that instead of returning nil.
    if @fallback_tag != nil
      # Substitute any placeholders in our rewrite tag
      result_rewritetag = @fallback_tag.gsub(/(\${[a-z_]+(\[[0-9]+\])?}|__[A-Z_]+__)/) do
        log.warn("rewrite_tag_file_filter: unknown placeholder found. :placeholder=>#{$1} :tag=>#{tag} :rewritetag=>#{rewritetag}") unless placeholder.include?($1)
        placeholder[$1]
      end
      return result_rewritetag
    else
      # No match.
      return nil
    end ## if @fallback_tag

  end ## rewrite_tag

  def regexp_last_match(regexp, rewritevalue)
    if rewritevalue.valid_encoding?
      regexp.match(rewritevalue)
    else
      regexp.match(rewritevalue.scrub('?'))
    end
  end ## regexp_last_match

  def get_backreference_table(elements)
    hash_table = Hash.new
    elements.each.with_index(1) do |value, index|
      hash_table["$#{index}"] = @capitalize_regex_backreference ? value.capitalize : value
    end
    return hash_table
  end

  def get_placeholder(tag)
    tag = tag.sub(@remove_tag_prefix, '') if @remove_tag_prefix

    result = {
      '__HOSTNAME__' => @hostname,
      '${hostname}' => @hostname,
      '__TAG__' => tag,
      '${tag}' => tag,
    }

    tag.split('.').each_with_index do |t, idx|
      result.store("${tag_parts[#{idx}]}", t)
      result.store("__TAG_PARTS[#{idx}]__", t)
    end

    return result
  end
end

**Comment by okkez** [comment]
This plugin applies only one rule matched first.
If you want to apply multiple rules for one record, you can use multiple `<match>` section that has `@type rewrite-tag-filter`.

**Comment by Tesseract242** [comment]
I do apologise, the problem was to do with the source information not the rewrite-tag-filter.

I will close this case, thanks.
